from __future__ import annotations

from funnel.review_schema import (
    BOT_STATE_HEADERS,
    BOT_STATE_SHEET,
    CONGRESS_LEDGER_HEADERS,
    CONGRESS_LEDGER_SHEET,
    POLITICAL_DIGEST_LOG_HEADERS,
    POLITICAL_DIGEST_LOG_SHEET,
    POLITICAL_DIGEST_SNAPSHOT_HEADERS,
    POLITICAL_DIGEST_SNAPSHOT_SHEET,
    POLITICAL_TICKER_SUMMARY_HEADERS,
    POLITICAL_TICKER_SUMMARY_SHEET,
    POLITICAL_TRADES_RAW_HEADERS,
    POLITICAL_TRADES_RAW_SHEET,
    BTD_CANDIDATE_HEADERS,
    BTD_CANDIDATES_SHEET,
    DECISION_LOG_HEADERS,
    DECISION_LOG_SHEET,
    FEROLDI_AI_DRAFT_HEADERS,
    FEROLDI_AI_DRAFTS_SHEET,
    FEROLDI_FIRST_CUT_DETAIL_HEADERS,
    FEROLDI_FIRST_CUT_DETAIL_SHEET,
    INSIDER_LEDGER_HEADERS,
    INSIDER_LEDGER_SHEET,
    MANUAL_SEED_HEADERS,
    MANUAL_SEED_SHEET,
    SIGNAL_LOG_HEADERS,
    SIGNAL_LOG_SHEET,
)
from funnel.sheet_table import ensure_sheet


def ensure_review_sheets(service, spreadsheet_id: str) -> None:
    sheets = [
        (SIGNAL_LOG_SHEET, SIGNAL_LOG_HEADERS),
        (BTD_CANDIDATES_SHEET, BTD_CANDIDATE_HEADERS),
        (FEROLDI_AI_DRAFTS_SHEET, FEROLDI_AI_DRAFT_HEADERS),
        (FEROLDI_FIRST_CUT_DETAIL_SHEET, FEROLDI_FIRST_CUT_DETAIL_HEADERS),
        (BOT_STATE_SHEET, BOT_STATE_HEADERS),
        (DECISION_LOG_SHEET, DECISION_LOG_HEADERS),
        (MANUAL_SEED_SHEET, MANUAL_SEED_HEADERS),
        (CONGRESS_LEDGER_SHEET, CONGRESS_LEDGER_HEADERS),
        (POLITICAL_TRADES_RAW_SHEET, POLITICAL_TRADES_RAW_HEADERS),
        (POLITICAL_TICKER_SUMMARY_SHEET, POLITICAL_TICKER_SUMMARY_HEADERS),
        (POLITICAL_DIGEST_LOG_SHEET, POLITICAL_DIGEST_LOG_HEADERS),
        (POLITICAL_DIGEST_SNAPSHOT_SHEET, POLITICAL_DIGEST_SNAPSHOT_HEADERS),
        (INSIDER_LEDGER_SHEET, INSIDER_LEDGER_HEADERS),
    ]
    for sheet_name, headers in sheets:
        ensure_sheet(service, spreadsheet_id, sheet_name, headers)
