from __future__ import annotations

from datetime import datetime, timezone


MASTERLIST_SHEET = "Stock Summary USD"
SIGNAL_LOG_SHEET = "Signal_Log"
BTD_CANDIDATES_SHEET = "BTD_Candidates"
FEROLDI_AI_DRAFTS_SHEET = "Feroldi_AI_Drafts"
BOT_STATE_SHEET = "Bot_State"
DECISION_LOG_SHEET = "Decision_Log"
MANUAL_SEED_SHEET = "Manual_Seed_Tickers"
CONGRESS_LEDGER_SHEET = "Congress_Ledger"
POLITICAL_TRADES_RAW_SHEET = "Political_Trades_Raw"
POLITICAL_TICKER_SUMMARY_SHEET = "Political_Ticker_Summary"
POLITICAL_DIGEST_LOG_SHEET = "Political_Digest_Log"
INSIDER_LEDGER_SHEET = "Insider_Ledger"
FEROLDI_FIRST_CUT_DETAIL_SHEET = "Feroldi_First_Cut_Detail"


CANDIDATE_ACTIVE_STATUSES = {
    "NEW",
    "ENRICHED",
    "BTD_PASSED",
    "BTD_FAILED",
    "BTD_UNAVAILABLE",
    "BTD_NOT_APPLICABLE",
    "FEROLDI_PASSED",
    "FEROLDI_REVIEW",
    "FEROLDI_FAILED",
    "FEROLDI_UNAVAILABLE",
    "RESEARCH_NOW",
    "WAITING_CONFIRMATION",
    "WATCH",
    "NOTIFIED",
    "REVIEW",
}

CANDIDATE_FINAL_STATUSES = {
    "APPROVED_ADDED",
    "APPROVED_ALREADY_EXISTS",
    "REJECTED",
    "ARCHIVED",
}


SIGNAL_LOG_HEADERS = [
    "Run ID",
    "Signal ID",
    "Ticker",
    "Source",
    "Classification",
    "Signal Score",
    "Observed At",
    "Valid Until",
    "Reason",
    "Details JSON",
    "Created At",
]


BTD_CANDIDATE_HEADERS = [
    "Candidate ID",
    "Ticker",
    "Company Name",
    "Google Ticker",
    "Status",
    "Review Priority",
    "Source",
    "Positive Sources",
    "Risk Sources",
    "Corroboration Level",
    "Conflict Status",
    "Attention Family",
    "Technical Confirmation",
    "Ownership Confirmation",
    "Forward Confirmation",
    "Forward Confirmation Score",
    "Forward Confirmation Detail",
    "Thesis Breaker Severity",
    "Thesis Breaker Detail",
    "Research Rank",
    "Research Rank Bucket",
    "Decision Lane",
    "Decision Lane Reason",
    "Risk Flags",
    "Thesis Summary",
    "Supporting Classifications",
    "Supporting Scores",
    "Supporting Reasons",
    "Supporting Signal IDs",
    "Classification",
    "Funnel Score",
    "Signal Count",
    "Discovery Reason",
    "Congress Unique Members",
    "Congress Recent Cluster Members",
    "Congress Active Purchases",
    "Congress Member Names",
    "Insider Total Score",
    "Insider Conviction",
    "Insider Economic Commitment",
    "Insider Market Context",
    "Insider Unique Insiders",
    "Insider Roles",
    "Insider Aggregate Purchase",
    "Insider Cluster Span Days",
    "Insider Weighted Purchase Price",
    "Insider Entry State",
    "Fundamental Inflection Classification",
    "Fundamental Inflection Score",
    "Fundamental Inflection Pillars",
    "Fundamental Inflection Revenue Growth",
    "Fundamental Inflection Growth Acceleration",
    "Fundamental Inflection Gross Margin Change Bps",
    "Fundamental Inflection Operating Margin Change Bps",
    "Fundamental Inflection FCF Margin Change Bps",
    "Fundamental Inflection Diluted Share Growth",
    "Fundamental Inflection Cash Runway Months",
    "Fundamental Inflection Risk Flags",
    "Fundamental Inflection Reason",
    "First Seen",
    "Last Seen",
    "BTD Score",
    "BTD Ratio",
    "BTD Summary",
    "BTD Applicability",
    "BTD Gate",
    "BTD Gate Reason",
    "Telegram Eligible",
    "Next Earnings Date",
    "Enterprise Value",
    "Total Revenue",
    "EBITDA Margin",
    "Revenue Growth",
    "Gross Margin",
    "Employees",
    "BTD Last Updated",
    "AI Feroldi Score",
    "AI Quality Summary",
    "AI Bull Case",
    "AI Bear Case",
    "AI Red Flags",
    "AI Manual Review Needed",
    "AI Confidence",
    "AI Last Updated",
    "Telegram Message ID",
    "Telegram Last Notified At",
    "Telegram Last Notified Signature",
    "Telegram Last Notified Lane",
    "Previous Decision Lane",
    "Decision Lane Last Changed At",
    "Thesis Last Changed At",
    "Thesis Change Count",
    "Decision",
    "Decision At",
    "Decision By",
    "Manual Override",
    "Manual Verdict",
    "Why Interesting",
    "What Must Be True",
    "What Would Invalidate",
    "Next Check Date",
    "Last Error",
    "Active?",
    "EV (B)",
    "Revenue TTM (B)",
    "Gross Margin %",
    "Revenue Growth %",
    "BTD Formula",
    "Feroldi Financial Score",
    "Feroldi Financial Available",
    "Feroldi Management Score",
    "Feroldi Management Available",
    "Feroldi Stock Score",
    "Feroldi Stock Available",
    "Feroldi First Cut Score",
    "Feroldi Available Points",
    "Feroldi Max Points",
    "Feroldi Equivalent Score",
    "Feroldi Coverage",
    "Feroldi Score Display",
    "Feroldi Missing Inputs",
    "Feroldi Gate Mode",
    "Feroldi Gate",
    "Feroldi Gate Reason",
    "Feroldi Last Updated",
    "Feroldi F03 Trajectory",
    "Feroldi F04 Trajectory",
    "Feroldi F05 Trajectory",
    "Feroldi F03 Weighted ROE Growth %",
    "Feroldi F04 Weighted FCF Growth %",
    "Feroldi F05 Weighted EPS Growth %",
]


FEROLDI_AI_DRAFT_HEADERS = [
    "Candidate ID",
    "Ticker",
    "AI Feroldi Score",
    "Quality Summary",
    "Bull Case",
    "Bear Case",
    "Red Flags",
    "Manual Review Needed",
    "Confidence",
    "Draft JSON",
    "Created At",
]


BOT_STATE_HEADERS = [
    "Key",
    "Value",
    "Updated At",
]


DECISION_LOG_HEADERS = [
    "Decision ID",
    "Candidate ID",
    "Ticker",
    "Action",
    "Actor",
    "Telegram Update ID",
    "Decision At",
    "Result",
    "Details",
]


MANUAL_SEED_HEADERS = [
    "Ticker",
    "Reason",
    "Score",
    "Status",
    "Added At",
]


CONGRESS_LEDGER_HEADERS = [
    "Trade Key",
    "Fingerprint",
    "Ticker",
    "Transaction Date",
    "Filing Date",
    "Last Seen At",
    "Last Seen Payload Hash",
]


POLITICAL_TRADES_RAW_HEADERS = [
    "Trade Key",
    "Source Trade ID",
    "Fingerprint",
    "Source ID",
    "Filing ID",
    "Filer ID",
    "Filer Name",
    "Branch",
    "Chamber",
    "Party",
    "State",
    "Agency",
    "Level",
    "Office",
    "Owner",
    "Owner Relationship",
    "Ticker",
    "Yahoo Ticker",
    "Asset Name",
    "Asset Type",
    "Asset Class",
    "Asset Intent Class",
    "Transaction Type",
    "Action",
    "Option Side",
    "Strike",
    "Expiry",
    "Amount Low",
    "Amount Mid Estimate",
    "Amount High",
    "Amount Range Label",
    "Transaction Date",
    "Filing Date",
    "Notification Date",
    "Ingested At",
    "Transaction Age",
    "Filing Age",
    "Days To File",
    "Late Filing Status",
    "Company Specific",
    "Bullish",
    "Bearish",
    "Broad Market",
    "Discretionary Weight",
    "Intentionality Score",
    "Broad Outcome",
    "Reason",
    "Proposed Resolution",
    "Manual Review Required",
    "Comments",
    "Description",
    "Filing Type",
    "Document URL",
    "Trigger Type",
    "First Seen At",
    "Last Seen At",
    "Last Changed At",
    "Record Version",
    "Is Materially Amended",
    "Last Seen Payload Hash",
    "Active In Latest Payload",
]


POLITICAL_TICKER_SUMMARY_HEADERS = [
    "Ticker",
    "Primary Classification",
    "Structure Classification",
    "Previous Classification",
    "Classification Changed",
    "Bullish Evidence Score",
    "Distribution Evidence Score",
    "Breadth Score",
    "Concentration Score",
    "Inference Confidence",
    "Data Confidence",
    "45D Purchases",
    "45D Partial Sales",
    "45D Full Sales",
    "45D Unique Buyers",
    "45D Unique Sellers",
    "45D Stock Purchase Low",
    "45D Stock Purchase Mid Estimate",
    "45D Stock Purchase High",
    "45D Call Purchase Low",
    "45D Call Purchase Mid Estimate",
    "45D Call Purchase High",
    "45D Put Purchase Low",
    "45D Put Purchase Mid Estimate",
    "45D Put Purchase High",
    "45D Sale Low",
    "45D Sale Mid Estimate",
    "45D Sale High",
    "90D Purchases",
    "90D Partial Sales",
    "90D Full Sales",
    "90D Unique Buyers",
    "90D Unique Sellers",
    "90D Stock Purchase Low",
    "90D Stock Purchase Mid Estimate",
    "90D Stock Purchase High",
    "90D Call Purchase Low",
    "90D Call Purchase Mid Estimate",
    "90D Call Purchase High",
    "90D Put Purchase Low",
    "90D Put Purchase Mid Estimate",
    "90D Put Purchase High",
    "90D Sale Low",
    "90D Sale Mid Estimate",
    "90D Sale High",
    "365D Purchases",
    "365D Partial Sales",
    "365D Full Sales",
    "365D Unique Buyers",
    "365D Unique Sellers",
    "Largest Bullish Trade Low",
    "Largest Bullish Trade High",
    "Largest Buyer Share Lower Bound",
    "Largest Buyer Share Midpoint Estimate",
    "Repeat Buyer Count",
    "Possible Exit Count",
    "Latest Transaction Date",
    "Latest Filing Date",
    "Latest Trigger Type",
    "Latest Trigger Trade Keys",
    "Latest Flag Reasons",
    "Political Conviction",
    "Entry Quality",
    "Summary Hash",
    "Last Updated",
]


POLITICAL_DIGEST_LOG_HEADERS = [
    "Digest Date",
    "Run ID",
    "Ticker",
    "Flag Rank",
    "Flag Category",
    "Flag Reasons",
    "Previous Classification",
    "Current Classification",
    "Summary Hash",
    "Trigger Trade Keys",
    "Release Types",
    "Telegram Included",
    "Telegram Sent At",
    "Payload Hash",
    "Created At",
]


INSIDER_LEDGER_HEADERS = [
    "Record Key",
    "Transaction Key",
    "Transaction Group Key",
    "Source Fingerprint",
    "Accession",
    "Issuer CIK",
    "Ticker",
    "Owner CIK",
    "Owner Name",
    "Owner Role",
    "Officer Title",
    "Owner Is Operating",
    "Owner Is Director",
    "Owner Is Officer",
    "Owner Is Ten Percent Owner",
    "Transaction Date",
    "Filing Date",
    "Security Title",
    "Shares",
    "Price Per Share",
    "Transaction Value",
    "Direct Or Indirect",
    "Plan 10b5-1",
    "Shares Owned After",
    "Decision",
    "Reason",
    "Confidence",
    "Qualification Decision",
    "Qualification Reason",
    "Superseded By",
    "Observed At",
]

FEROLDI_FIRST_CUT_DETAIL_HEADERS = [
    "Candidate ID",
    "Ticker",
    "Company Name",
    "Google Ticker",
    "Feroldi Rubric Version",
    "Feroldi As Of Date",
    "Reporting Currency",
    "Data Jurisdiction",
    "CIK",
    "Extraction Status",
    "Missing Inputs",
    "Manual Review Required",
    "Last Error",
    "Created At",
    "Last Updated",
    # F01
    "F01 Cash And Cash Equivalents",
    "F01 Long Term Debt",
    "F01 Cash To Long Term Debt Ratio",
    "F01 No Long Term Debt Flag",
    "F01 Score",
    "F01 Available",
    "F01 Reason",
    "F01 Source",
    "F01 Source Period",
    "F01 Source Date",
    # F02
    "F02 Revenue TTM",
    "F02 Cost Of Revenue TTM",
    "F02 Gross Profit TTM",
    "F02 Gross Margin %",
    "F02 Score",
    "F02 Available",
    "F02 Reason",
    "F02 Source",
    "F02 Source Period",
    "F02 Source Date",
    # F03
    "F03 Current Net Income TTM",
    "F03 Current Opening Equity",
    "F03 Current Closing Equity",
    "F03 Current Average Equity",
    "F03 Current ROE %",
    "F03 Prior Net Income TTM",
    "F03 Prior Opening Equity",
    "F03 Prior Closing Equity",
    "F03 Prior Average Equity",
    "F03 Prior ROE %",
    "F03 Two Year Net Income TTM",
    "F03 Two Year ROE %",
    "F03 ROE Growth %",
    "F03 Weighted ROE Growth %",
    "F03 Trajectory Label",
    "F03 Turnaround Flag",
    "F03 Valid Equity Flag",
    "F03 Score",
    "F03 Available",
    "F03 Reason",
    "F03 Source",
    "F03 Source Period",
    "F03 Source Date",
    # F04
    "F04 Current Operating Cash Flow TTM",
    "F04 Current Capital Expenditure TTM",
    "F04 Current Free Cash Flow TTM",
    "F04 Prior Operating Cash Flow TTM",
    "F04 Prior Capital Expenditure TTM",
    "F04 Prior Free Cash Flow TTM",
    "F04 Two Year Operating Cash Flow TTM",
    "F04 Two Year Capital Expenditure TTM",
    "F04 Two Year Free Cash Flow TTM",
    "F04 FCF Growth %",
    "F04 Weighted FCF Growth %",
    "F04 Trajectory Label",
    "F04 Turnaround Flag",
    "F04 Score",
    "F04 Available",
    "F04 Reason",
    "F04 Source",
    "F04 Source Period",
    "F04 Source Date",
    # F05
    "F05 Current Diluted EPS TTM",
    "F05 Prior Diluted EPS TTM",
    "F05 Two Year Diluted EPS TTM",
    "F05 EPS Growth %",
    "F05 Weighted EPS Growth %",
    "F05 Trajectory Label",
    "F05 Turnaround Flag",
    "F05 Score",
    "F05 Available",
    "F05 Reason",
    "F05 Source",
    "F05 Source Period",
    "F05 Source Date",
    # M01
    "M01 Current CEO Name",
    "M01 CEO Appointment Date",
    "M01 CEO Appointment Year",
    "M01 CEO Date Precision",
    "M01 CEO Tenure Years",
    "M01 Founder Flag",
    "M01 Cofounder Flag",
    "M01 Founding Family Flag",
    "M01 Interim CEO Flag",
    "M01 External Hire Flag",
    "M01 Evidence Text",
    "M01 Primary Source Type",
    "M01 Primary Source Filing Date",
    "M01 Primary Source Accession",
    "M01 Primary Source URL",
    "M01 Conflict Flag",
    "M01 Extraction Confidence",
    "M01 Score",
    "M01 Available",
    "M01 Reason",
    "M01 Last Updated",
    # M02
    "M02 CEO Beneficial Shares",
    "M02 Basic Shares Outstanding",
    "M02 CEO Ownership %",
    "M02 Current Share Price",
    "M02 CEO Stake Value USD",
    "M02 Directors And Officers Group %",
    "M02 Ownership Basis",
    "M02 Score",
    "M02 Available",
    "M02 Reason",
    "M02 Source Type",
    "M02 Source Date",
    "M02 Source URL",
    "M02 Extraction Confidence",
    # M03
    "M03 Mission Text",
    "M03 Source Type",
    "M03 Source URL",
    "M03 Source Date",
    "M03 Extraction Phrase",
    "M03 Extraction Confidence",
    "M03 Word Count",
    "M03 Sentence Count",
    "M03 Structural Punctuation Count",
    "M03 Parenthetical Count",
    "M03 Action Verb Found",
    "M03 Object Or Offering Found",
    "M03 Beneficiary Found",
    "M03 Outcome Found",
    "M03 Undefined Acronym Count",
    "M03 Vague Term Count",
    "M03 Financial Only Flag",
    "M03 Simple Point",
    "M03 Clear Point",
    "M03 Inspirational Point",
    "M03 Score",
    "M03 Available",
    "M03 Reason",
    "M03 Last Updated",
    # S01
    "S01 Measurement Start Date",
    "S01 Measurement End Date",
    "S01 Stock Start Adjusted Price",
    "S01 Stock End Adjusted Price",
    "S01 SPY Start Adjusted Price",
    "S01 SPY End Adjusted Price",
    "S01 Stock Total Return %",
    "S01 SPY Total Return %",
    "S01 Excess Return Percentage Points",
    "S01 Trading Days",
    "S01 Short Listing Flag",
    "S01 Score",
    "S01 Available",
    "S01 Reason",
    "S01 Source",
    # S02
    "S02 Share Repurchases TTM",
    "S02 Share Issuance TTM",
    "S02 Net Repurchases TTM",
    "S02 Market Capitalisation",
    "S02 Net Repurchases To Market Cap %",
    "S02 Diluted Shares Current",
    "S02 Diluted Shares Prior",
    "S02 Diluted Share Change %",
    "S02 Dividend Per Share TTM",
    "S02 Dividend Per Share Prior",
    "S02 Dividend Growth %",
    "S02 Dividend Cut Flag",
    "S02 Dividend Data Valid Flag",
    "S02 Total Debt Current",
    "S02 Total Debt Prior",
    "S02 Debt Change %",
    "S02 Total Assets",
    "S02 Effectively Debt Free Flag",
    "S02 Buyback Point",
    "S02 Buyback Available",
    "S02 Dividend Point",
    "S02 Dividend Available",
    "S02 Debt Reduction Point",
    "S02 Debt Reduction Available",
    "S02 Score",
    "S02 Available",
    "S02 Reason",
    "S02 Source",
    "S02 Source Date",
    # S03
    "S03 Q1 Fiscal Period",
    "S03 Q1 Report Date",
    "S03 Q1 Reported EPS",
    "S03 Q1 Estimated EPS",
    "S03 Q1 Absolute Surprise",
    "S03 Q1 Surprise %",
    "S03 Q1 Point",
    "S03 Q2 Fiscal Period",
    "S03 Q2 Report Date",
    "S03 Q2 Reported EPS",
    "S03 Q2 Estimated EPS",
    "S03 Q2 Absolute Surprise",
    "S03 Q2 Surprise %",
    "S03 Q2 Point",
    "S03 Q3 Fiscal Period",
    "S03 Q3 Report Date",
    "S03 Q3 Reported EPS",
    "S03 Q3 Estimated EPS",
    "S03 Q3 Absolute Surprise",
    "S03 Q3 Surprise %",
    "S03 Q3 Point",
    "S03 Q4 Fiscal Period",
    "S03 Q4 Report Date",
    "S03 Q4 Reported EPS",
    "S03 Q4 Estimated EPS",
    "S03 Q4 Absolute Surprise",
    "S03 Q4 Surprise %",
    "S03 Q4 Point",
    "S03 Score",
    "S03 Available",
    "S03 Reason",
    "S03 Source",
    "S03 Source Date",
]


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()
