from __future__ import annotations

import logging
import os
import sys
from typing import Any

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Core guardrail: NO_LLM_DECISIONS
# ---------------------------------------------------------------------------

_DEFAULT_NO_LLM = True  # default to true per spec


def _env_bool(name: str, default: bool) -> bool:
    raw = str(os.getenv(name, "")).strip().lower()
    if not raw:
        return default
    return raw not in {"0", "false", "no", "off"}


def no_llm_decisions() -> bool:
    """Return True when LLM-based decision logic is disabled."""
    return _env_bool("NO_LLM_DECISIONS", _DEFAULT_NO_LLM)


def require_no_llm() -> None:
    """Raise RuntimeError if NO_LLM_DECISIONS is not enabled.

    Call this at module import time in any decision-critical module.
    When NO_LLM_DECISIONS=true (default), this is a no-op.
    """
    if not no_llm_decisions():
        raise RuntimeError(
            "NO_LLM_DECISIONS=false is not supported by decision-critical modules. "
            "All investment decisions must be deterministic. "
            "Set NO_LLM_DECISIONS=true to continue."
        )


# ---------------------------------------------------------------------------
# LLM endpoint blocklist
# ---------------------------------------------------------------------------

_KNOWN_LLM_ENDPOINTS = frozenset({
    "api.openai.com",
    "api.anthropic.com",
    "generativelanguage.googleapis.com",
    "api.gemini.google.com",
    "api.together.xyz",
    "api.mistral.ai",
    "api.perplexity.ai",
    "api.cohere.ai",
    "api.cohere.com",
    "openrouter.ai",
    "api.deepseek.com",
    "api.x.ai",
    "api.groq.com",
    "llmfoundry.studio",
    "aiapi.anthropic.com",
    "inference.anthropic.com",
})


def is_known_llm_endpoint(url: str) -> bool:
    """Return True if the URL targets a known LLM provider."""
    normalized = str(url or "").strip().lower()
    for endpoint in _KNOWN_LLM_ENDPOINTS:
        if endpoint in normalized:
            return True
    return False


def raise_if_feroldi_ai_imported() -> None:
    """Runtime invariant: raise RuntimeError if feroldi_ai is imported in decision paths.

    Call this at the entry point of any decision-critical workflow.
    """
    if not no_llm_decisions():
        return

    imported = check_feroldi_ai_not_in_decision_path()
    if imported:
        raise RuntimeError(
            f"NO_LLM_DECISIONS=true but feroldi_ai modules are imported: "
            f"{', '.join(imported)}. "
            "Decision-critical workflows must not import AI modules."
        )


def check_feroldi_ai_not_in_decision_path() -> list[str]:
    """Verify that feroldi_ai is NOT imported when NO_LLM_DECISIONS is True.

    Returns a list of imported AI modules found (empty = clean).
    """
    if not no_llm_decisions():
        return []

    imported: list[str] = []
    for mod in sorted(sys.modules):
        clean = mod.lower()
        if "feroldi_ai" in clean:
            imported.append(mod)

    if imported:
        logger.warning(
            "WARNING: feroldi_ai modules are imported while NO_LLM_DECISIONS=true: %s. "
            "AI fields must be optional narrative-only fields that never influence decisions.",
            ", ".join(imported),
        )

    return imported


# ---------------------------------------------------------------------------
# AI field invalidation: ensure AI fields never affect decisions
# ---------------------------------------------------------------------------

_AI_FIELD_NAMES = frozenset({
    "AI Feroldi Score",
    "AI Quality Summary",
    "AI Bull Case",
    "AI Bear Case",
    "AI Red Flags",
    "AI Manual Review Needed",
    "AI Confidence",
    "AI Last Updated",
})


def is_ai_field(field_name: str) -> bool:
    """Return True if the field is generated by an LLM."""
    normalized = str(field_name or "").strip()
    return normalized in _AI_FIELD_NAMES


def strip_ai_fields(candidate: dict[str, Any]) -> dict[str, Any]:
    """Remove all AI-generated fields from a candidate record.

    Use this in decision-critical code paths to ensure AI fields
    never influence gates, scores, or recommendations.
    """
    return {
        key: value
        for key, value in candidate.items()
        if not is_ai_field(key)
    }


# ---------------------------------------------------------------------------
# Runtime invariant checks
# ---------------------------------------------------------------------------


def check_production_safeguards() -> list[str]:
    """Run all production safeguards and return any warnings.

    Returns empty list when all checks pass.
    """
    warnings: list[str] = []

    if no_llm_decisions():
        check_feroldi_ai_not_in_decision_path()

    if os.getenv("OPENAI_API_KEY", "").strip() and no_llm_decisions():
        warnings.append(
            "OPENAI_API_KEY is set but NO_LLM_DECISIONS=true. "
            "AI drafts will still run but must not influence decisions."
        )

    return warnings


__all__ = [
    "no_llm_decisions",
    "require_no_llm",
    "is_known_llm_endpoint",
    "is_ai_field",
    "strip_ai_fields",
    "check_feroldi_ai_not_in_decision_path",
    "raise_if_feroldi_ai_imported",
    "check_production_safeguards",
    "_KNOWN_LLM_ENDPOINTS",
    "_AI_FIELD_NAMES",
]
